from typing import Any, Optional

from .base import ViewInspector


class SwaggerAutoSchema(ViewInspector):
    operation_keys: Any = ...

    def __init__(
        self,
        view: Any,
        path: Any,
        method: Any,
        components: Any,
        request: Any,
        overrides: Any,
        operation_keys: Optional[Any] = ...,
    ): ...
    def get_operation(self, operation_keys: Optional[Any] = ...) -> Any: ...
    def get_request_body_parameters(self, consumes: Any) -> Any: ...
    def get_view_serializer(self) -> Any: ...
    def get_request_serializer(self) -> Any: ...
    def get_request_form_parameters(self, serializer: Any) -> Any: ...
    def get_request_body_schema(self, serializer: Any) -> Any: ...
    def make_body_parameter(self, schema: Any) -> Any: ...
    def add_manual_parameters(self, parameters: Any) -> Any: ...
    def get_responses(self) -> Any: ...
    def get_default_response_serializer(self) -> Any: ...
    def get_default_responses(self) -> Any: ...
    def get_response_serializers(self) -> Any: ...
    def get_response_schemas(self, response_serializers: Any) -> Any: ...
    def get_query_serializer(self) -> Any: ...
    def get_query_parameters(self) -> Any: ...
    def get_operation_id(self, operation_keys: Optional[Any] = ...) -> Any: ...
    def split_summary_from_description(self, description: Any) -> Any: ...
    def get_summary_and_description(self) -> Any: ...
    def get_security(self) -> Any: ...
    def is_deprecated(self) -> Any: ...
    def get_tags(self, operation_keys: Optional[Any] = ...) -> Any: ...
    def get_consumes(self) -> Any: ...
    def get_produces(self) -> Any: ...
