# Generated by Django 3.0.3 on 2020-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_category', models.CharField(max_length=30)),
                ('photo_detail', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
