# Generated by Django 3.0.3 on 2020-06-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='images/None/no-img,jpg', upload_to='images/%Y/%m/%d'),
        ),
    ]
